var annotated_dup =
[
    [ "ros1_bridge", null, [
      [ "ActionFactory_1_2", "classros1__bridge_1_1ActionFactory__1__2.html", "classros1__bridge_1_1ActionFactory__1__2" ],
      [ "ActionFactory_2_1", "classros1__bridge_1_1ActionFactory__2__1.html", "classros1__bridge_1_1ActionFactory__2__1" ],
      [ "Bridge1to2Handles", "structros1__bridge_1_1Bridge1to2Handles.html", null ],
      [ "Bridge2to1Handles", "structros1__bridge_1_1Bridge2to1Handles.html", null ],
      [ "BridgeHandles", "structros1__bridge_1_1BridgeHandles.html", null ],
      [ "Factory", "classros1__bridge_1_1Factory.html", null ],
      [ "ServiceFactory", "classros1__bridge_1_1ServiceFactory.html", null ],
      [ "ServiceBridge1to2", "structros1__bridge_1_1ServiceBridge1to2.html", null ],
      [ "ServiceBridge2to1", "structros1__bridge_1_1ServiceBridge2to1.html", null ],
      [ "FactoryInterface", "classros1__bridge_1_1FactoryInterface.html", null ],
      [ "ServiceFactoryInterface", "classros1__bridge_1_1ServiceFactoryInterface.html", null ],
      [ "ActionFactoryInterface", "classros1__bridge_1_1ActionFactoryInterface.html", null ],
      [ "Message", "classros1__bridge_1_1Message.html", null ],
      [ "MappingRule", "classros1__bridge_1_1MappingRule.html", null ],
      [ "MessageMappingRule", "classros1__bridge_1_1MessageMappingRule.html", null ],
      [ "ServiceMappingRule", "classros1__bridge_1_1ServiceMappingRule.html", null ],
      [ "ActionMappingRule", "classros1__bridge_1_1ActionMappingRule.html", null ],
      [ "ActionSpec", "classros1__bridge_1_1ActionSpec.html", null ],
      [ "Mapping", "classros1__bridge_1_1Mapping.html", "classros1__bridge_1_1Mapping" ],
      [ "MessageIndex", "classros1__bridge_1_1MessageIndex.html", "classros1__bridge_1_1MessageIndex" ]
    ] ],
    [ "Bridge1to2HandlesAndMessageTypes", "structBridge1to2HandlesAndMessageTypes.html", null ],
    [ "Bridge2to1HandlesAndMessageTypes", "structBridge2to1HandlesAndMessageTypes.html", null ],
    [ "Circle_line", "structCircle__line.html", null ],
    [ "CMDPublisher", "classCMDPublisher.html", "classCMDPublisher" ],
    [ "Curves_struct", "structCurves__struct.html", null ],
    [ "Dubins_arc", "structDubins__arc.html", null ],
    [ "Dubins_curve", "structDubins__curve.html", null ],
    [ "HardwareGlobalInterface", "classHardwareGlobalInterface.html", "classHardwareGlobalInterface" ],
    [ "HardwareParameters", "structHardwareParameters.html", "structHardwareParameters" ],
    [ "Joystick", "classJoystick.html", "classJoystick" ],
    [ "JoystickEvent", "classJoystickEvent.html", "classJoystickEvent" ],
    [ "PathPublisher", "classPathPublisher.html", null ],
    [ "Plot_arc_struct", "structPlot__arc__struct.html", null ],
    [ "Scale_from_standard", "structScale__from__standard.html", null ],
    [ "Scale_to_standard", "structScale__to__standard.html", null ],
    [ "ShelfinoHWNode", "classShelfinoHWNode.html", "classShelfinoHWNode" ]
];